---
kind: pipeline
name: ci

platform:
  os: linux
  arch: amd64

steps:
- name: ci
  image: rancher/dapper:v0.5.3
  commands:
  - dapper ci
  environment:
    GIT_IN_DAPPER: true
    DOCKER_PASS:
      from_secret: docker_password
    DOCKER_USER:
      from_secret: docker_username
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - tag
  instance:
    - drone-publish.rancher.io

- name: validate
  image: rancher/dapper:v0.5.3
  commands:
  - dapper validate
  environment:
    GIT_IN_DAPPER: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    instance:
    - drone-pr.rancher.io


- name: build
  image: rancher/dapper:v0.5.3
  commands:
  - dapper build
  environment:
    GIT_IN_DAPPER: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    instance:
    - drone-pr.rancher.io


- name: test
  image: rancher/dapper:v0.5.3
  commands:
  - dapper test
  environment:
    GIT_IN_DAPPER: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    instance:
    - drone-pr.rancher.io

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
