#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running tests

FIND_COMMAND="find"
if [ "$(go env GOHOSTOS)" = "darwin" ]; then
  FIND_COMMAND="find ."
fi

PACKAGES="$($FIND_COMMAND -name '*.go' | xargs -I{} dirname {} | sort -u | grep -Ev '(^\.$|.git|.trash-cache|vendor|bin|docs|test|controller/store|images|examples|hack)')"

go test -v -p 1 -tags "cgo" -cover ${PACKAGES}
