name: release

on:
  push:
    tags:
      - '*'

jobs:

  rancher-ci:
    runs-on: ubuntu-latest
    container:
      image: rancher/dapper:v0.5.3
      env:
        GIT_IN_DAPPER: true
        DOCKER_USER: ${{ secrets.docker_username }}
        DOCKER_PASS: ${{ secrets.docker_password }}
    steps:
      - name: Add git
        run: |
          apk add --no-cache git

      - name: Checkout
        uses: actions/checkout@v2

      - name: tag
        run: |
          dapper ci
